-- ── settings ───────────────────────────────────────────────────────────
hs.autoLaunch(true)
hs.automaticallyCheckForUpdates(false)
hs.menuIcon(false)
hs.consoleOnTop(false)

-- ── palette (generated by Nix) ────────────────────────────────────────
local palette = dofile(hs.configdir .. "/palette.lua")

-- ── app scanner ───────────────────────────────────────────────────────
local appDirs = {
  "/Applications",
  "/System/Applications",
  "/System/Applications/Utilities",
  os.getenv("HOME") .. "/Applications",
  os.getenv("HOME") .. "/Applications/Home Manager Apps",
}

local function findApps()
  local seen, items = {}, {}
  for _, dir in ipairs(appDirs) do
    local iter, dirObj = hs.fs.dir(dir)
    if iter then
      for file in iter, dirObj do
        if file:match("%.app$") and not seen[file] then
          seen[file] = true
          local appPath = dir .. "/" .. file
          table.insert(items, { name = file:gsub("%.app$", ""), path = appPath })
        end
      end
    end
  end
  table.sort(items, function(a, b)
    return a.name:lower() < b.name:lower()
  end)
  return items
end

-- ── webview (created once, reused) ────────────────────────────────────
local W, H = 640 + 48, 420 + 48 -- 24px shadow margin on each side

local function launcherRect()
  local screen = hs.screen.mainScreen():frame()
  return hs.geometry.rect((screen.w - W) / 2, screen.h / 4, W, H)
end

local uc = hs.webview.usercontent.new("launcher")
local wv = hs.webview.new(launcherRect(), { developerExtrasEnabled = false }, uc)
wv:windowStyle({ "borderless", "nonactivating" })
wv:transparent(true)
wv:allowTextEntry(true)
wv:level(hs.canvas.windowLevels.floating)
wv:url("file://" .. hs.configdir .. "/launcher.html")

-- ── focus / hide helpers ──────────────────────────────────────────────
local prevApp = nil

local function hideLauncher()
  wv:hide()
  if prevApp then
    prevApp:activate()
    prevApp = nil
  end
end

-- ── hide on focus loss ────────────────────────────────────────────────
-- Permanently subscribed with an isVisible() guard. Do NOT subscribe/unsubscribe
-- on show/hide — wf:subscribe() forces a full window list rebuild and adds ~2s
-- of latency to the show path. A no-op callback while hidden is far cheaper.
local wf = hs.window.filter.new(false):setDefaultFilter({})
wf:subscribe(hs.window.filter.windowFocused, function(win)
  if not wv:isVisible() then
    return
  end
  local wvWin = wv:hswindow()
  if wvWin and win:id() == wvWin:id() then
    return
  end
  hideLauncher()
end)

-- ── Lua -> JS helpers ─────────────────────────────────────────────────
local function pushTheme()
  local style = (hs.host.interfaceStyle() or "Light"):lower()
  local colors = palette[style]
  local parts = {}
  for k, v in pairs(colors) do
    table.insert(parts, string.format("'%s':'%s'", k, v))
  end
  wv:evaluateJavaScript(string.format("window.setTheme({%s})", table.concat(parts, ",")))
end

local function pushApps()
  local apps = findApps()
  wv:evaluateJavaScript(string.format("window.loadApps(%s)", hs.json.encode(apps)))
  -- deferred to next runloop iteration to avoid blocking the show
  hs.timer.doAfter(0, function()
    local icons = {}
    for _, app in ipairs(apps) do
      local img = hs.image.iconForFile(app.path)
      if img then
        icons[app.path] = img:setSize({ w = 32, h = 32 }):encodeAsURLString()
      end
    end
    wv:evaluateJavaScript(string.format("window.loadIcons(%s)", hs.json.encode(icons)))
  end)
end

-- ── JS -> Lua handler ─────────────────────────────────────────────────
uc:setCallback(function(msg)
  local body = hs.json.decode(msg.body)
  if body.action == "ready" then
    pushTheme()
    pushApps()
  elseif body.action == "launch" then
    wv:hide()
    prevApp = nil
    hs.application.open(body.path)
  elseif body.action == "hide" then
    hideLauncher()
  end
end)

-- ── theme watcher ─────────────────────────────────────────────────────
hs.distributednotifications
  .new(function()
    -- delay: interfaceStyle() is not yet updated when this notification fires
    hs.timer.doAfter(0.1, pushTheme)
  end, "AppleInterfaceThemeChangedNotification")
  :start()

-- ── reload: URL handler (triggered by nix-rebuild) + hotkey ──────────
hs.urlevent.bind("reload", function()
  hs.reload()
end)
hs.hotkey.bind({ "ctrl", "alt", "cmd", "shift" }, "r", hs.reload)

-- ── hotkey: alt+space toggles the launcher ────────────────────────────
hs.hotkey.bind({ "alt" }, "space", function()
  if wv:isVisible() then
    hideLauncher()
  else
    prevApp = hs.application.frontmostApplication()
    wv:frame(launcherRect())
    wv:evaluateJavaScript("window.activate()")
    wv:show()
    local win = wv:hswindow()
    if win then
      win:focus()
    end
  end
end)
